SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF SCHEMA_ID(N'retail') IS NULL EXEC(N'CREATE SCHEMA retail AUTHORIZATION dbo;');
GO
IF SCHEMA_ID(N'retail_ops') IS NULL EXEC(N'CREATE SCHEMA retail_ops AUTHORIZATION dbo;');
GO
